services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dunkhub
    ports:
      - "5432:5432"
    volumes:
      - dunkhub_db:/var/lib/postgresql/data

volumes:
  dunkhub_db:
